import Head from 'next/head'
import Footer from '../components/docs/views/footer'
import Hero from '../components/docs/views/hero'

export default function Home () {
  return (
    <>
      <Head>
        <title>Development Tools</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='docs-container'>
        <main className='docs-main'>
          <Hero />
        </main>
        <Footer />
      </div>
    </>
  )
}
